#!/usr/bin/env python3
"""Bundle policy fixture tests, not a native macOS compilation/launch claim."""
import importlib.util
import json
from pathlib import Path
import plistlib
import tempfile
import sys
from unittest.mock import patch

# Importing the packaging helper must not dirty the source checkout with generated bytecode.
sys.dont_write_bytecode = True
script = Path(__file__).resolve().parent / 'package-macos.py'
spec = importlib.util.spec_from_file_location('package_macos', script)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

with tempfile.TemporaryDirectory(prefix='pipkin-mac-bundle-test-') as temporary:
    root = Path(temporary)
    files = {'Cargo.toml': '[workspace.package]\nversion = "0.0.1"\n',
             'target/release/pipkin': 'fixture binary', 'LICENSE': 'MIT fixture',
             'SECURITY.md': 'security fixture', 'assets/PROVENANCE.md': 'asset fixture',
             'assets/fonts/example-OFL.txt': 'font fixture',
             'docs/macos-first-pass.md': 'experimental instructions',
             'packaging/pi-engine-revision': 'a' * 40,
             'dist/macos-notices/usr/share/doc/pipkin/third-party/inventory.json': '{}',
             'dist/macos-notices/usr/share/doc/pipkin/third-party/sources/mpl/src/lib.rs': 'exact source'}
    for relative, text in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    (root / 'target/release/pipkin').chmod(0o755)

    def output(args, **kwargs):
        if args[:2] == ['git', 'rev-parse']:
            return 'b' * 40 + '\n'
        if args[:2] == ['git', 'status']:
            return b''
        if args[0] == 'otool':
            return '/private/fixture/executable:\n\t/usr/lib/libSystem.B.dylib (compatibility version 1.0.0)\n'
        raise AssertionError(args)

    def archive(args, **kwargs):
        assert args[:5] == ['ditto', '-c', '-k', '--sequesterRsrc', '--keepParent']
        contents = Path(args[-2]) / 'Contents'
        assert (contents / 'MacOS/pipkin').stat().st_mode & 0o111
        assert plistlib.loads((contents / 'Info.plist').read_bytes())['CFBundleExecutable'] == 'pipkin'
        assert (contents / 'Resources/third-party/sources/mpl/src/lib.rs').read_text() == 'exact source'
        assert (contents / 'Resources/font-notices/example-OFL.txt').exists()
        Path(args[-1]).write_bytes(b'fixture zip')

    with patch.object(module, 'ROOT', root), patch.object(module.sys, 'platform', 'darwin'), patch.object(module.sys, 'argv', [str(script), 'aarch64-apple-darwin']), patch.object(module.subprocess, 'check_output', side_effect=output), patch.object(module.subprocess, 'run', side_effect=archive):
        module.main()
        out = root / 'dist/macos'
        info = json.loads((out / 'build-info.json').read_text())
        assert info['experimental'] and not info['engine']['bundled']
        assert info['app']['target'] == 'aarch64-apple-darwin'
        assert info['app']['revision'] == 'b' * 40 and info['app']['dirty'] is False
        assert info['app']['binarySha256'] == module.sha256(root / 'target/release/pipkin')
        assert 'Developer ID' in info['signing']
        assert temporary not in (out / 'build-info.json').read_text()
        assert '/private/fixture' not in (out / 'build-info.json').read_text()
        assert not (out / 'Pipkin.app').exists()
        package = next(out.glob('*.zip'))
        assert (out / 'SHA256SUMS').read_text() == f'{module.sha256(package)}  {package.name}\n'
        module.main()  # An identified prior output can be replaced.
    with patch.object(module.sys, 'platform', 'linux'):
        try:
            module.main()
            raise AssertionError('non-macOS packaging was accepted')
        except SystemExit as error:
            assert 'native build on macOS' in str(error)
print('macOS bundle/notice/source/identity/checksum policy fixtures passed; no native build claimed')
