#!/usr/bin/env python3
"""Bundle policy fixture tests, not a native macOS compilation/launch claim."""
import importlib.util
import hashlib
import json
from pathlib import Path
import plistlib
import shutil
import subprocess
import zipfile
import tempfile
import sys
from unittest.mock import patch

# Importing the packaging helper must not dirty the source checkout with generated bytecode.
sys.dont_write_bytecode = True
script = Path(__file__).resolve().parent / 'package-macos.py'
spec = importlib.util.spec_from_file_location('package_macos', script)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

with tempfile.TemporaryDirectory(prefix='pipkin-mac-bundle-test-') as temporary:
    root = Path(temporary)
    files = {'Cargo.toml': '[workspace.package]\nversion = "0.0.1"\n',
             'target/release/pipkin': 'fixture binary', 'LICENSE': 'MIT fixture',
             'SECURITY.md': 'security fixture', 'assets/PROVENANCE.md': 'asset fixture',
             'packaging/pipkin.icns': 'fixture app icon',
             'assets/fonts/example-OFL.txt': 'font fixture',
             'docs/macos-first-pass.md': 'experimental instructions',
             'packaging/pi-engine-revision': 'a' * 40,
             'dist/macos-notices/usr/lib/pipkin/engine/engine.json': json.dumps({'sourceRevision': 'a' * 40, 'development': False, 'productionPruneSucceeded': True}),
             'dist/macos-notices/usr/lib/pipkin/engine/pi-test.sh': 'fixture launcher',
             'dist/macos-notices/usr/lib/pipkin/runtime/bin/node': 'fixture node',
             'dist/macos-notices/usr/lib/pipkin/runtime/LICENSE': 'full Node notice',
             'dist/macos-notices/usr/lib/pipkin/runtime/runtime.json': json.dumps({'target': 'aarch64-apple-darwin', 'version': '22.23.3', 'binarySha256': hashlib.sha256(b'fixture node').hexdigest()}),
             'dist/macos-notices/usr/share/doc/pipkin/third-party/inventory.json': '{}',
             'dist/macos-notices/usr/share/doc/pipkin/third-party/sources/mpl/src/lib.rs': 'exact source'}
    for relative, text in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    (root / 'target/release/pipkin').chmod(0o755)

    def output(args, **kwargs):
        if args[:2] == ['git', 'rev-parse']:
            return 'b' * 40 + '\n'
        if args[:2] == ['git', 'status']:
            return b''
        if args[0] == 'otool':
            return '/private/fixture/executable:\n\t/usr/lib/libSystem.B.dylib (compatibility version 1.0.0)\n'
        raise AssertionError(args)

    calls = []
    corrupt_extraction = False
    corrupt_dmg = False
    fail_attach = False
    dmg_payload = None

    def seal(contents):
        return {str(p.relative_to(contents)): module.sha256(p) for p in contents.rglob('*')
                if p.is_file() and '_CodeSignature' not in p.parts}

    def command(args, **kwargs):
        global dmg_payload
        if args[:2] == ['hdiutil', 'detach'] and 'stdout' in kwargs:
            assert kwargs['check'] is False  # Cleanup after a partially successful attach.
        else:
            assert kwargs['check'] is True
        calls.append(args)
        if args[:2] == ['codesign', '--force']:
            assert args[2:6] == ['--sign', '-', '--identifier', 'org.last-refuge.pipkin']
            contents = Path(args[-1]) / 'Contents'
            executable = contents / 'MacOS/pipkin'
            executable.write_bytes(executable.read_bytes() + b' fixture signature')
            signature = contents / '_CodeSignature/CodeResources'
            signature.parent.mkdir()
            signature.write_text(json.dumps(seal(contents)))
        elif args[:2] == ['codesign', '--verify']:
            assert args[2:5] == ['--deep', '--strict', '--verbose=4']
            contents = Path(args[-1]) / 'Contents'
            if json.loads((contents / '_CodeSignature/CodeResources').read_text()) != seal(contents):
                raise subprocess.CalledProcessError(1, args)
        elif args[:5] == ['ditto', '-c', '-k', '--sequesterRsrc', '--keepParent']:
            bundle = Path(args[-2]); contents = bundle / 'Contents'
            assert (contents / 'MacOS/pipkin').stat().st_mode & 0o111
            plist = plistlib.loads((contents / 'Info.plist').read_bytes())
            assert plist['CFBundleExecutable'] == 'pipkin'
            assert plist['CFBundleIconFile'] == 'pipkin.icns'
            assert (contents / 'Resources/pipkin.icns').read_text() == 'fixture app icon'
            assert (contents / 'Resources/third-party/sources/mpl/src/lib.rs').read_text() == 'exact source'
            assert (contents / 'Resources/font-notices/example-OFL.txt').exists()
            embedded = json.loads((contents / 'Resources/build-info.json').read_text())
            assert 'binarySha256' not in embedded['app']  # No self-referential signature hash.
            assert embedded['app']['preBundleSigningBinarySha256'] == module.sha256(root / 'target/release/pipkin')
            with zipfile.ZipFile(args[-1], 'w') as archive:
                for path in bundle.rglob('*'):
                    if path.is_file():
                        archive.write(path, path.relative_to(bundle.parent))
        elif args[:3] == ['ditto', '-x', '-k']:
            with zipfile.ZipFile(args[3]) as archive:
                archive.extractall(args[4])
            if corrupt_extraction:
                (Path(args[4]) / 'Pipkin.app/Contents/Resources/README.md').write_text('tampered resource')
        elif args[:2] == ['hdiutil', 'create']:
            assert args[2:5] == ['-volname', 'Pipkin', '-srcfolder']
            assert args[6:9] == ['-format', 'UDZO', '-ov']
            payload = Path(args[5])
            assert sorted(p.name for p in payload.iterdir()) == ['Applications', 'Pipkin.app']
            assert (payload / 'Applications').is_symlink()
            assert (payload / 'Applications').readlink() == Path('/Applications')
            dmg_payload = payload
            Path(args[-1]).write_bytes(b'fixture disk image')
        elif args[:2] == ['hdiutil', 'attach']:
            assert args[2:6] == ['-readonly', '-nobrowse', '-mountpoint', args[5]]
            assert Path(args[-1]).read_bytes() == b'fixture disk image'
            mount = Path(args[5])
            shutil.copytree(dmg_payload / 'Pipkin.app', mount / 'Pipkin.app', symlinks=True)
            (mount / 'Applications').symlink_to('/Applications', target_is_directory=True)
            if corrupt_dmg:
                (mount / 'Pipkin.app/Contents/Resources/README.md').write_text('tampered image')
            if fail_attach:
                raise subprocess.CalledProcessError(1, args)
        elif args[:2] == ['hdiutil', 'detach']:
            assert Path(args[2]).is_dir()
        elif '--diagnose' in args:
            assert '--probe' in args
            assert kwargs['env']['PATH'] == '/usr/bin:/bin:/usr/sbin:/sbin'
            assert set(kwargs['env']) == {'PATH', 'HOME', 'TMPDIR', 'PI_OFFLINE'}
            contents = Path(args[0]).parent.parent
            assert json.loads((contents / 'lib/pipkin/engine/engine.json').read_text())['requiresBundledNode']
            assert (contents / 'lib/pipkin/runtime/LICENSE').read_text() == 'full Node notice'
        else:
            raise AssertionError(args)

    with patch.object(module, 'ROOT', root), patch.object(module.sys, 'platform', 'darwin'), patch.object(module.sys, 'argv', [str(script), 'aarch64-apple-darwin']), patch.object(module.subprocess, 'check_output', side_effect=output), patch.object(module.subprocess, 'run', side_effect=command):
        module.main()
        out = root / 'dist/macos'
        info = json.loads((out / 'build-info.json').read_text())
        assert info['experimental'] and info['engine']['bundled']
        assert info['nodeRuntime']['version'] == '22.23.3'
        assert info['app']['target'] == 'aarch64-apple-darwin'
        assert info['app']['revision'] == 'b' * 40 and info['app']['dirty'] is False
        assert info['app']['preBundleSigningBinarySha256'] == module.sha256(root / 'target/release/pipkin')
        assert info['app']['binarySha256'] != info['app']['preBundleSigningBinarySha256']
        assert sum(args[:2] == ['codesign', '--verify'] for args in calls) == 5
        assert 'Developer ID' in info['signing']
        assert temporary not in (out / 'build-info.json').read_text()
        assert '/private/fixture' not in (out / 'build-info.json').read_text()
        assert not (out / 'Pipkin.app').exists()
        package = next(out.glob('*.zip'))
        dmg = next(out.glob('*.dmg'))
        assert (out / 'SHA256SUMS').read_text() == (
            f'{module.sha256(package)}  {package.name}\n{module.sha256(dmg)}  {dmg.name}\n')
        assert sum('--probe' in args for args in calls) == 2  # Extracted ZIP and copied DMG app.
        module.main()  # An identified prior output can be replaced.
        corrupt_dmg = True
        before = sum(args[:2] == ['hdiutil', 'detach'] for args in calls)
        try:
            module.main()
            raise AssertionError('tampered mounted app was accepted')
        except subprocess.CalledProcessError:
            assert sum(args[:2] == ['hdiutil', 'detach'] for args in calls) == before + 1
            assert not (out / 'SHA256SUMS').exists()
        corrupt_dmg = False
        fail_attach = True
        before = sum(args[:2] == ['hdiutil', 'detach'] for args in calls)
        try:
            module.main()
            raise AssertionError('failed attach was accepted')
        except subprocess.CalledProcessError:
            assert sum(args[:2] == ['hdiutil', 'detach'] for args in calls) == before + 1
            assert not (out / 'SHA256SUMS').exists()
        fail_attach = False
        corrupt_extraction = True
        try:
            module.main()
            raise AssertionError('tampered extracted resources were accepted')
        except subprocess.CalledProcessError:
            assert not (out / 'SHA256SUMS').exists()  # Do not publish a failed bundle.
    with patch.object(module.sys, 'platform', 'linux'):
        try:
            module.main()
            raise AssertionError('non-macOS packaging was accepted')
        except SystemExit as error:
            assert 'native build on macOS' in str(error)
print('macOS bundle/notice/source/identity/checksum policy fixtures passed; no native build claimed')
